### PR TITLE
This vagrantifies the app

### PR DESCRIPTION
**Pull request by jasiek**

### CODE REVIEW

**Comment by russss** [comment]
You shouldn't need to check out the code within the Vagrant machine - the project directory should already be shared to /vagrant in the VM. Otherwise it looks reasonable.

**Comment by jasiek** [comment]
You're right, let me rework this.

**Comment by jasiek** [comment]
Updated, can you have another look?

**Comment by russss** [comment]
Looks good now. I've got a slight preference against creating the DB (I sometimes test locally with a copy of production data), but I'll fix that when I merge my postgres branch.

**Pull request merged**
